version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: recipe_auth

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.dev
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.dev'

        #? Define entrypoint
        entrypoint: 'npm run start:auth[dev]'

        #? Restart if down
        restart: always

        #? Volumes
        volumes:
            - "./recipe:/app/recipe"

        #? Ports
        ports:
            - ${RECIPE_AUTH_PORT}:${RECIPE_AUTH_PORT}

        #? Container dependencies
        depends_on:
            - db

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: recipe_api

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.dev
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.dev'

        #? Define entrypoint
        entrypoint: 'npm run start:api[dev]'

        #? Restart if down
        restart: always

        #? Volumes
        volumes:
            - "./recipe:/app/recipe"

        #? Ports
        ports:
            - ${RECIPE_API_PORT}:${RECIPE_API_PORT}

        #? Container dependencies
        depends_on:
            - db
        
    db:
        container_name: recipe_db
        image: postgres
        restart: always
        env_file:
            - "./.env.db"
        ports:
            - "5432:5432"