version: "3.5"
services:
    postgres:
        container_name: recipe_db
        image: postgres
        restart: always
        env_file:
            - "./.env.db"
        ports:
            - "5432:5432"