name: Build and push the recipe_app backend to Dockerhub

on: 
  push:
    branches: [main]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into main
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Grab version from .env file 
        run: |
          VER=$(  grep RECIPE_VERSION .env | cut -f 2 -d "=" | tr "\"" "\n" )
          echo "USERNAME=saptaktdk123" >> $GITHUB_ENV
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "REPO=recipe" >> $GITHUB_ENV
      
      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/Dockerfile.prod
          platform: linux/amd64
          push: true
          tags: ${{ env.USERNAME }}/${{ env.REPO }}:${{ env.VERSION }}
